### ISSUE TITLE
通過user.txt下載的個人主頁視頻，結束進程以後檔案全都是0KB

### ISSUE THREAD

**Issue by Victorzheng520** [erma0/douyin#17]

**Comment by erma0** [comment]
无法复现，能否提供测试链接

**Comment by Victorzheng520** [comment]
> 无法复现，能否提供测试链接

https://v.douyin.com/U3exN7A
https://v.douyin.com/U3exXkJ
https://v.douyin.com/U3eAtXx
https://v.douyin.com/U3JoKby
https://v.douyin.com/U3eDNP2
https://v.douyin.com/U3eNA2E

**Comment by Victorzheng520** [comment]
![Image_20230615131254](https://github.com/erma0/douyin/assets/59199786/b157a5c6-0409-493f-89ec-8c18bab58f01)

**Comment by Victorzheng520** [comment]
Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe... 1 (char 0)')>) at playwright\_impl\_sync_base.py:100
handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe... 1 (char 0)')>) at playwright\_impl\_sync_base.py:100>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "playwright\_impl\_sync_base.py", line 100, in <lambda>
  File "playwright\_impl\_helper.py", line 273, in impl
  File "playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
  File "spider.py", line 277, in handle
  File "playwright\sync_api\_generated.py", line 18128, in json
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_fetch.py", line 464, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Victorzheng520** [comment]
douyin -u https://v.douyin.com/U3eAtXx/

    ____                    _         ____        _     _
|  _ \  ___  _   _ _   _(_)_ __   / ___| _ __ (_) __| | ___ _ __
| | | |/ _ \| | | | | | | | '_ \  \___ \| '_ \| |/ _` |/ _ \ '__|
| |_| | (_) | |_| | |_| | | | | |  ___) | |_) | | (_| |  __/ |
|____/ \___/ \__,_|\__, |_|_| |_| |____/| .__/|_|\__,_|\___|_|
                    |___/                |_|
                                V3.2
                Github: https://github.com/erma0/douyin

2023-06-15 15:01:44.529 | INFO     | spider:_append_awemes:197 - 采集中，已采集到17条结果
2023-06-15 15:01:44.686 | ERROR    | spider:handle:275 - err：  Expecting value: line 1 column 1 (char 0)
Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe... 1 (char 0)')>) at playwright\_impl\_sync_base.py:100
handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe... 1 (char 0)')>) at playwright\_impl\_sync_base.py:100>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "playwright\_impl\_sync_base.py", line 100, in <lambda>
  File "playwright\_impl\_helper.py", line 273, in impl
  File "playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
  File "spider.py", line 277, in handle
  File "playwright\sync_api\_generated.py", line 18128, in json
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_fetch.py", line 464, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-06-15 15:01:46.562 | ERROR    | spider:run:386 - 重试 + 1
2023-06-15 15:01:48.582 | ERROR    | spider:run:386 - 重试 + 1
2023-06-15 15:01:50.598 | ERROR    | spider:run:386 - 重试 + 1
2023-06-15 15:01:52.612 | ERROR    | spider:run:386 - 重试 + 1
2023-06-15 15:01:54.636 | ERROR    | spider:run:386 - 重试 + 1
2023-06-15 15:01:56.664 | ERROR    | spider:run:386 - 重试 + 1
2023-06-15 15:01:56.671 | SUCCESS  | spider:save:216 - 采集完成，本次共采集到17条结果
2023-06-15 15:01:56.679 | INFO     | spider:download:207 - 开始下载
[DL:0B][#32f666 0B/0B][#f83942 0B/0B][#88ae03 0B/0B]
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
b4213e|OK  |       0B/s|./下载/post_派大欣/7244161601719356705_是这样扭吗#浅跳一下_#大长腿_#扭一扭_#慢摇_#不露脸系列.mp4
3e6eb0|OK  |       0B/s|./下载/post_派大欣/7244753803281501472_👌#浅跳一下_#扭一扭_#大长腿_#康复运动_#不露脸系列.mp4
41c8f9|OK  |       0B/s|./下载/post_派大欣/7242673784564501799_不会#浅跳一下_#扭一扭_#这样跳能俘获你的芳心吗_#日常摇一摇_#康复运动.mp4
980404|OK  |       0B/s|./下载/post_派大欣/7242204460938726694_这墙真白#浅跳一下_#扭一扭_#不露脸系列.mp4
a0a2df|OK  |       0B/s|./下载/post_派大欣/7242196700255751456_还是喜欢这个发型#浅跳一下_#扭一扭_#这样跳能俘获你的芳心吗.mp4
13d8a2|OK  |       0B/s|./下载/post_派大欣/7241936830977887521_在没有你的来电#浅跳一下_#日常摇一摇.mp4
618100|OK  |       0B/s|./下载/post_派大欣/7241803568959851779_太阳大的眼睛都睁不开##浅跳一下_#夏天的味道_#扭一扭.mp4
63cec7|OK  |       0B/s|./下载/post_派大欣/7240345650574019873_#扭一扭_#浅跳一下_#甜妹.mp4
78d896|OK  |       0B/s|./下载/post_派大欣/7238562346929589515_回复_@Suica的评论__可以啊.mp4
c059c6|OK  |       0B/s|./下载/post_派大欣/7233267159479143680_#浅跳一下_#扭一扭_#慢摇.mp4
0c9a01|OK  |       0B/s|./下载/post_派大欣/7227658632303840546_好甜噜～#甜妹_#甜甜的舞怎能少了甜甜的你_#浅跳一下.mp4
15182f|OK  |       0B/s|./下载/post_派大欣/7228230415369112832_来晚了#浅跳一下_#这才是甜妹该跳的舞.mp4
3c8cb5|OK  |       0B/s|./下载/post_派大欣/7221775795000315176_小朋友们准备好了吗#可爱到爆炸💥_#浅跳一下_#dou来休息一下.mp4
f2964d|OK  |       0B/s|./下载/post_派大欣/7223586551802989876_#浅跳一下_#dou来休息一下#五一穿搭.mp4
32f666|OK  |       0B/s|./下载/post_派大欣/7243628439419342119_闻你的味道～#浅跳一下_#慢摇_#大长腿_#不露脸系列_#康复运动.mp4
88ae03|OK  |       0B/s|./下载/post_派大欣/7242952526746701095_嘿嘿嘿OK#浅跳一下_#扭一扭_#不露脸系列_#康复运动_#大长腿.mp4
f83942|OK  |       0B/s|./下载/post_派大欣/7243348402556161319_这怎么扭#浅跳一下_#大长腿_#慢摇_#甜妹配硬曲_#不露脸系列.mp4

Status Legend:
(OK):download completed.



下載以後就變成 0kb了，但是任務也結束了

**Comment by erma0** [comment]
本地无法复现，建议尝试#18 的办法，或者等晚一点我加进去

**Comment by erma0** [comment]
仍旧无法复现，原因不明，猜测机器环境的问题，有同样问题的参考 #18 的办法，issue先关闭了。
