### ISSUE TITLE
大佬，这个Douyin.info为空，怎么解决啊？

### ISSUE THREAD

**Issue by CNWenwuGong** [erma0/douyin#36]
**运行环境：**

- 系统:  Linux
- 浏览器: Chrome
- 使用方式: 自己编译的

**运行命令：**
> 请提供你运行的命令（主要是测试链接地址）以便复现问题

```
./douyin -b chrome -n 2 -u https://www.douyin.com/user/MS4wLjABAAAA_ELoNs05CNtn3foI5YZnvV25tlVectip3-uFFokqq_iSUtS6jakIkOBzSVMn5vc5?vid=7312361433088445730
```

**问题描述：**
采集时报错说Douyin对象的info属性为空
> 详细说明出现什么问题
前几天还好好的能采集，今天就采集不了了，报错以下信息：
Traceback (most recent call last):
  File "exec.py", line 91, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "exec.py", line 74, in main
  File "exec.py", line 83, in start
  File "spider.py", line 513, in run
  File "spider.py", line 449, in page_init
AttributeError: 'Douyin' object has no attribute 'info'

**Comment by luoshui-coder** [comment]
附议，是不是抖音后台接口变了，这个项目大佬不维护了嘛

**Comment by hkcxz** [comment]
> **运行环境：**
> 
> * 系统:  Linux
> * 浏览器: Chrome
> * 使用方式: 自己编译的
> 
> **运行命令：**
> 
> > 请提供你运行的命令（主要是测试链接地址）以便复现问题
> 
> ```
> ./douyin -b chrome -n 2 -u https://www.douyin.com/user/MS4wLjABAAAA_ELoNs05CNtn3foI5YZnvV25tlVectip3-uFFokqq_iSUtS6jakIkOBzSVMn5vc5?vid=7312361433088445730
> ```
> 
> **问题描述：** 采集时报错说Douyin对象的info属性为空
> 
> > 详细说明出现什么问题
> > 前几天还好好的能采集，今天就采集不了了，报错以下信息：
> > Traceback (most recent call last):
> > File "exec.py", line 91, in 
> > File "click/core.py", line 1157, in **call**
> > File "click/core.py", line 1078, in main
> > File "click/core.py", line 1434, in invoke
> > File "click/core.py", line 783, in invoke
> > File "exec.py", line 74, in main
> > File "exec.py", line 83, in start
> > File "spider.py", line 513, in run
> > File "spider.py", line 449, in page_init
> > AttributeError: 'Douyin' object has no attribute 'info'

spider.py文件449行self.info是空的，取值取不到，就报错了；如果你文件夹命名格式不是title的话，手动给self.title设置一个值就ok了。我前几天遇到的问题是这样的。

**Comment by CNWenwuGong** [comment]
怎么设置，不太清楚，我不是做python开发的，只是集成了这个工具，不太清楚要改哪里

**Comment by CNWenwuGong** [comment]
> > **运行环境：**
> > 
> > * 系统:  Linux
> > * 浏览器: Chrome
> > * 使用方式: 自己编译的
> > 
> > **运行命令：**
> > > 请提供你运行的命令（主要是测试链接地址）以便复现问题
> > 
> > 
> > ```
> > ./douyin -b chrome -n 2 -u https://www.douyin.com/user/MS4wLjABAAAA_ELoNs05CNtn3foI5YZnvV25tlVectip3-uFFokqq_iSUtS6jakIkOBzSVMn5vc5?vid=7312361433088445730
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **问题描述：** 采集时报错说Douyin对象的info属性为空
> > > 详细说明出现什么问题
> > > 前几天还好好的能采集，今天就采集不了了，报错以下信息：
> > > Traceback (most recent call last):
> > > File "exec.py", line 91, in
> > > File "click/core.py", line 1157, in **call**
> > > File "click/core.py", line 1078, in main
> > > File "click/core.py", line 1434, in invoke
> > > File "click/core.py", line 783, in invoke
> > > File "exec.py", line 74, in main
> > > File "exec.py", line 83, in start
> > > File "spider.py", line 513, in run
> > > File "spider.py", line 449, in page_init
> > > AttributeError: 'Douyin' object has no attribute 'info'
> 
> spider.py文件449行self.info是空的，取值取不到，就报错了；如果你文件夹命名格式不是title的话，手动给self.title设置一个值就ok了。我前几天遇到的问题是这样的。

修改self.title后又出现以下错误：

python-BaseException
Traceback (most recent call last):
  File "F:\remoteworkspace\douyin-3\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "F:\remoteworkspace\douyin-3\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\remoteworkspace\douyin-3\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\remoteworkspace\douyin-3\exec.py", line 74, in main
    start(edge.context, url, num, grab, download, type, path, pathtype, mstoken)
  File "F:\remoteworkspace\douyin-3\exec.py", line 83, in start
    a.run()
  File "F:\remoteworkspace\douyin-3\spider.py", line 515, in run
    self.page_init()
  File "F:\remoteworkspace\douyin-3\spider.py", line 490, in page_init
    if self.type == 'post' and self.render_data.get('post', None):  # post页面需提取
                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:61:25)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at PipeTransport.send (F:\remoteworkspace\douyin-3\venv\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:51:21)
    at dispatcherConnection.onmessage (F:\remoteworkspace\douyin-3\venv\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:53:57)
    at DispatcherConnection._sendMessageToClient (F:\remoteworkspace\douyin-3\venv\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:201:10)
    at DispatcherConnection.sendEvent (F:\remoteworkspace\douyin-3\venv\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:164:10)
    at BrowserContextDispatcher._dispatchEvent (F:\remoteworkspace\douyin-3\venv\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:93:22)
    at CRBrowserContext.<anonymous> (F:\remoteworkspace\douyin-3\venv\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\browserContextDispatcher.js:132:12)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

**Comment by liaowenwu** [comment]
解决了吗  这个问题，我也遇到了

**Comment by CNWenwuGong** [comment]
没解决
