### ISSUE TITLE
运行报SyntaxError，求助

### ISSUE THREAD

**Issue by scutls** [erma0/douyin#50]
**运行环境：**

- 系统: Win10
- 使用方式: Python / exe  

**运行命令：**
E:\>douyin.exe -u https://www.douyin.com/user/MS4wLjABAAAAThMlRPGOobrrcMWtPnIqYKq90nCHHpijv5poXZdrBzU -t video

**问题描述：**
使用python和exe都报这个错误
没写过js，这个格式错误好像是js内部的问题？

Traceback (most recent call last):
  File "cli.py", line 78, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "cli.py", line 64, in main
  File "cli.py", line 69, in start
  File "douyin.py", line 58, in run
  File "douyin.py", line 190, in get_aweme_detail
  File "utils\request.py", line 148, in getJSON
  File "utils\request.py", line 97, in get_sign
  File "execjs\_abstract_runtime_context.py", line 37, in call
  File "execjs\_external_runtime.py", line 92, in _call
  File "execjs\_external_runtime.py", line 78, in _eval
  File "execjs\_abstract_runtime_context.py", line 18, in exec_
  File "execjs\_external_runtime.py", line 88, in _exec_
  File "execjs\_external_runtime.py", line 167, in _extract_result
execjs._exceptions.ProgramError: SyntaxError: 缺少 ')'
[15328] Failed to execute script 'cli' due to unhandled exception!

**Comment by erma0** [comment]
-t video 是用作单个视频的，下载作品用 post或不写
