### ISSUE TITLE
只采集最近更新的几个视频

### ISSUE THREAD

**Issue by quan8tum** [erma0/douyin#8]
你好，请问如何只采集最近更新的几个视频呢？现在的-l 5参数得到的不是最新的视频。

另外使用douyin.exe -t https://....，登录后，本目录下生成的auth.json文件，里面的内容是{"cookies": null}，下次再运行时需要删除这个文件再重新登录，否则会报错。

Traceback (most recent call last):
  File "douyin.py", line 322, in <module>
  File "click\core.py", line 1130, in __call__
  File "click\core.py", line 1055, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 760, in invoke
  File "douyin.py", line 298, in main
  File "douyin.py", line 305, in start
  File "douyin.py", line 230, in run
  File "playwright\sync_api\_generated.py", line 14048, in new_context
  File "playwright\_impl\_sync_base.py", line 104, in _sync
  File "playwright\_impl\_browser.py", line 126, in new_context
  File "playwright\_impl\_connection.py", line 61, in send
  File "playwright\_impl\_connection.py", line 461, in wrap_api_call
  File "playwright\_impl\_connection.py", line 96, in inner_send
playwright._impl._api_types.Error: storageState.cookies: expected array, got object
[9872] Failed to execute script 'douyin' due to unhandled exception!

**Comment by erma0** [comment]
最新视频可以自己根据ID排序一下，因为很多作者有设置的置顶作品，另外只采集前几个视频的话，没必要用浏览器，好像直接请求主页就能拿到数据，具体我没测试，建议试试。
> 内容是{"cookies": null}
这个应该是我写错了，取回的cookie会出现弹窗，所以我手动加了一条cookie，看了一下代码好像没返回值，正好要新增一个关注粉丝列表采集，等下午再一起改一下吧。

**Comment by erma0** [comment]
已更新，在限制采集数量时（比如采集5个参数为 -n 5）自动排序，忽略作品置顶，以便于查看最新作品
